### ISSUE TITLE
Is it possible to set value for jsonpaths

### ISSUE THREAD

**Issue by ilkerc** [KittyMac/Sextant#1]
just as on `com.jayway.jsonpath.DocumentContext.set()`, are there any implementations for settings a value for given jsonpath ?

```
   /**
     * Set the value a the given path
     *
     * @param path      path to set
     * @param newValue  new value
     * @return a document context
     */
    DocumentContext set(JsonPath path, Object newValue);
```

**Comment by KittyMac** [comment]
There is not, but I can add it.  Probably this weekend.

**Comment by ilkerc** [comment]
@KittyMac sounds great, looking forward.

**Comment by KittyMac** [comment]
@ilkerc v0.4.0 is up and now supports this.

**Comment by KittyMac** [comment]
This can be more easily implemented like this:

```swift
let oldJson = #"{"someValue": ["elem1", "elem2", "elem3"]}"#
let newJson: String? = oldJson.query(map: "$.someValue", {_ in
    return ["elem4", "elem5"]
} ) { root in
    return root.description
}
XCTAssertEqual(newJson, #"{"someValue":["elem4","elem5"]}"#)
```

The return value from your map callback is auto-converted to a JsonElement for you, so you can return any json-like-thing and it should handle it.  This is more costly performance-wise (since it needs to use as? to determine what the thing is at runtime), but should be fine unless discover it is too slow fo your use case.

Spanker's performance comes from making a hierarchy of JsonElements who reference the memory in the original storage (like a bunch of SubStrings referencing a single String, these lightweight objects are cheap to make so long as they don't need to make copies). This is the reason for the .parsed(), as the source data is guaranteed to be live inside of it.

If you wanted to do the above more performantly, then we want to move the creation of the JsonElement outside of the map.  Like this:

```swift
let oldJson = #"{"someValue": ["elem1", "elem2", "elem3"]}"#
let replacementElement = JsonElement(unknown: ["elem4", "elem5"])
let newJson: String? = oldJson.query(map: "$.someValue", {_ in
    return replacementElement
} ) { root in
    return root.description
}
XCTAssertEqual(newJson, #"{"someValue":["elem4","elem5"]}"#)
``` 

If you really want to create the element from a string, you can indeed use Spanker like so:

```swift
let oldJson = #"{"someValue": ["elem1", "elem2", "elem3"]}"#
let replacementJson = #"["elem4", "elem5"]"#
let newJson: String? = replacementJson.parsed { replacementElement in
    return oldJson.query(map: "$.someValue", {_ in
        return replacementElement
    } ) { root in
        return root.description
    }
}
XCTAssertEqual(newJson, #"{"someValue":["elem4","elem5"]}"#)
```

**Comment by ilkerc** [comment]
@KittyMac these are very elegant solutions, especially initializing `JsonElement` with anything is very useful. Thanks!
